# shakimofu dark theme colors
# author: fairy_lettuce

[colors.primary]
foreground = "#eae3cf"
background = "#17130c"

[colors.normal]
black = "#1d1f21"
red = "#fb8969"
green = "#bede77"
yellow = "#edb567"
blue = "#79abd6"
magenta = "#b496e1"
cyan = "#94d9c5"
white = "#dcdcd9"

[colors.bright]
black = "#666666"
red = "#d54e53"
green = "#b9ca4a"
yellow = "#e7c547"
blue = "#7aa6da"
magenta = "#c397d8"
cyan = "#70c0b1"
white = "#eaeaea"
