[window]
opacity = 0.85

[font]
size = 12

[font.bold]
family = "Noto Sans Mono CJK JP"
style = "Bold"

[font.bold_italic]
family = "Noto Sans Mono CJK JP"
style = "Bold Italic"

[font.italic]
family = "Noto Sans Mono CJK JP"
style = "Italic"

[font.normal]
family = "Noto Sans Mono CJK JP"
style = "Regular"
